apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rqngu9v0u-python
  janus-idp.io/tekton: rqngu9v0u-python
  backstage.io/kubernetes-id: rqngu9v0u-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rqngu9v0u-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
